{% set name = "opentelemetry-sdk" %}
{% set version = "0.13b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 15f87b7e42551ccef3a3534ddf376fc323d0306d1233b9199eb4e9fe13d04c85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - opentelemetry-api =={{ version }}
    - python >=3.4

test:
  imports:
    - opentelemetry.sdk.metrics
    - opentelemetry.sdk.metrics.export
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
