{% set name = "opentelemetry-sdk" %}
{% set version = "0.14b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b6572dcc21a6718889af78b5ad79b8a0f4609f36f7ab26fc2acaf80d8452ce4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - opentelemetry-api =={{ version }}
    - python >=3.4

test:
  imports:
    - opentelemetry.sdk.metrics
    - opentelemetry.sdk.metrics.export
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/master/opentelemetry-sdk
  summary: OpenTelemetry Python SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
